import JSZip from 'jszip';
import { CodeType } from '../models/Generation';

const FILE_MAP: Record<CodeType, { filename: string; extension: string }> = {
  'html-website': { filename: 'index', extension: 'html' },
  'react-component': { filename: 'Component', extension: 'tsx' },
  'nextjs-page': { filename: 'page', extension: 'tsx' },
  'node-express-api': { filename: 'server', extension: 'ts' },
  'python-script': { filename: 'script', extension: 'py' },
  'arduino-code': { filename: 'sketch', extension: 'ino' },
  'full-stack': { filename: 'fullstack', extension: 'txt' },
};

export async function buildZip(
  code: string,
  codeType: CodeType,
  title: string
): Promise<Buffer> {
  const zip = new JSZip();
  const { filename, extension } = FILE_MAP[codeType];
  const sanitizedTitle = title.replace(/[^a-z0-9]/gi, '_').toLowerCase();

  zip.file(`${sanitizedTitle}/${filename}.${extension}`, code);
  zip.file(`${sanitizedTitle}/README.md`, buildReadme(title, codeType, code));

  return zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });
}

function buildReadme(title: string, codeType: string, code: string): string {
  const lineCount = code.split('\n').length;
  return `# ${title}

Generated by VoiceForge — Voice to Code Generator

## Type
${codeType}

## Stats
- Lines of code: ${lineCount}
- Generated: ${new Date().toISOString()}

## Usage

${getUsageInstructions(codeType as CodeType)}

---
*Generated with [VoiceForge](https://voiceforge.app)*
`;
}

function getUsageInstructions(codeType: CodeType): string {
  const instructions: Record<CodeType, string> = {
    'html-website': 'Open `index.html` in a browser, or deploy to any static host (Netlify, GitHub Pages, Vercel).',
    'react-component': 'Import the component into your React project. Make sure Tailwind CSS is configured.',
    'nextjs-page': 'Place `page.tsx` in your Next.js `app/` directory. Run `npm run dev` to view.',
    'node-express-api': 'Run `npm install && npx ts-node server.ts` or compile with TypeScript.',
    'python-script': 'Run with `python script.py`. Install any listed requirements with `pip install -r requirements.txt`.',
    'arduino-code': 'Open `sketch.ino` in the Arduino IDE and upload to your board.',
    'full-stack': 'See the labeled sections in the file for frontend, backend, and database setup.',
  };
  return instructions[codeType];
}
